### ISSUE TITLE
Developer chat

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/issues#1]
As @jukkae pointed out, doing all communicating through github issues can quickly become chaotic. A better idea is to do the discussions in a dedicated chatroom and write the conclusions in github issue comments.

A quick search on the web brought me to https://gitter.im. Integrates with Github and HuBoard. You can connect with your IRC client. It gives you unlimited chat history for 5 $/month.

**Comment by josteinaj** [comment]
There's also [Slack](https://slack.com/), [HipChat](https://www.hipchat.com/) and [Flowdock](https://www.flowdock.com/) which also seems pretty popular (as well as a bunch of others).

They all seem pretty popular, but I get the feeling that Slack is slightly more popular than the others?

Slack also has HuBoard integration it seems, although it's not listed in the list of integrations:
https://github.com/rauhryan/huboard/issues/324

There's only a native app for OS X though. For Windows and Linux there's the Chrome app (which integrates with the desktop etc. so it should be decent). It seems you can use Slack over IRC as well:
https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP

Gitter also only has a native app for OS X. I don't know how good the IRC bridge is. I don't use IRC for anything else, but I could probably use Pidgin or whatever for that. I'm guessing that native clients are better though?

On the other hand, HipChat has clients for all three OSes (trying to test it now, need to get a couple of ports opened in the firewall). It's also supposed to integrate with HuBoard:
https://github.com/rauhryan/huboard/issues/377

They all seem to have similar pricing.

**Comment by bertfrees** [comment]
Thanks Jostein. All we really need is basically a single chat box, preferably with unlimited history. But I admit all those fancy features (integration of this, integration of that, markdown support, syntax highlighting, screen sharing, file sharing, video chat, etc. etc.) are very tempting.

Let us know how you liked HipChat. I'm fine with a web interface or an IRC bridge by the way.

**Comment by josteinaj** [comment]
Got HipChat installed now. Seems decent, but I haven't tried it in practice and I'm not familiar with the other tools so I don't know what's best.

I think we should avoid anything that requires you to have a browser tab all the time. Not that any of those tools requires you to do so, but some of the advantage of a chat tool is that it's always running,  so you're always available, isn't it?

If all we want is to store the chat history, then there's always google talk.

**Comment by josteinaj** [comment]
(writing on mobile, pressed "comment" by mistake)

(...) always available, isn't it?

If all we want is to store the chat history, then there's always google talk.

**Comment by bertfrees** [comment]
OK good point about always being available.

With chat history I mean that the chat logs should be there for everyone to see even if they weren't in the chatbox at the time. If GTalk can do that, I guess that's fine.

**Comment by josteinaj** [comment]
Yeah I think it works like that, but I'm not sure. There's also facebook chat if we really want to go crazy.

I would be interested in trying out a dedicated tool though. Either HipChat since it has a working Linux client, or Slack/Gitter if IRC is sufficient. HipChat seems to be the most mature of the options since it's existed since 2010. Whatever we choose, we can start with the free option and upgrade if we like it?

**Comment by bertfrees** [comment]
Trying out Slack now...

**Comment by bertfrees** [comment]
IRC works (with SSL) and I have configured Github webhooks. If everything goes well there should be a notification in Slack after I've added this comment.

**Comment by egli** [comment]
If all we are doing is irc then I don't quite see why we just create a channel on freenet or oftc

**Comment by jukkae** [comment]
Are we? I am; irc's fine by me.

**Comment by josteinaj** [comment]
Slack works fine for me, but if all we want is chat then IRC is also fine. If all we want is chat then Skype is also an option though. If we want the chat history to be stored for future reference, then I don't think IRC/Skype are good options?

**Comment by egli** [comment]
For chat history someone would have to set up a irc logger. It is true that slack offers more than irc. Question is if we need more than what irc offers. From what I can see slack is a fancy (and proprietary) chat client that has notifications from a lot of sides, i.e. github issues, commits, etc

**Comment by bertfrees** [comment]
Conclusion of offline discussion: we are developers and like to do things ourselfs, but on the other hand there are hosted services out there that make our lifes easy ("the old hosted vs diy discussion aka easy vs privacy"). One problem with Slack is that we can't easily invite people to a chat that are not signed up, but there seem to be workarounds. A first investigation has shown us that setting up an irc logging bot is quite a hassle.

**Comment by egli** [comment]
After having slept on it I propose that we go for the simplest and still most convenient solution:
1. We create a channel on freenode for chat via irc
2. The channel is logged via an external service (https://botbot.me/)
3. non-nerd access is via http://webchat.freenode.net/
4. For code snippets we just use github gists

This solution is based on plain old, hassle-free irc while still featuring searchable logs and code snippet sharing. It is also very open, i.e. no invites etc. needed

**Comment by egli** [comment]
There is now a channel on freenode.net named #snaekobbi. The repos functional-testing and issues have services set up so that they should send notifications to the channel

**Comment by egli** [comment]
Just testing if irc notifications work

**Comment by bertfrees** [comment]
Because as it has turned out not everybody is as enthusiastic about IRC, a possibility is to sync our IRC channel with a Slack channel, as described in http://www.everybodyhertz.co.uk/slack-and-irc.
