### ISSUE TITLE
Install Pipeline version 1.9.1 on test server

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/issues#11]
In addition install all agency-specific braille modules (they are not included in the default distribution of Pipeline).

Maybe write an Ansible script for more automatic deployment to the test server (and possibly other servers such as the "repo" server). This will make life easier for Jostein and could allow us to deploy without him.

Depends on:
- [x] https://github.com/snaekobbi/system/issues/1

See also:
- [x] https://github.com/daisy/pipeline-assembly/issues/78
- [x] https://github.com/snaekobbi/issues/issues/12
- [x] https://github.com/snaekobbi/issues/issues/15
- [x] https://github.com/snaekobbi/pipeline-mod-celia/issues/1
- [x] https://github.com/snaekobbi/pipeline-mod-nota/issues/1
- [x] https://github.com/snaekobbi/pipeline-mod-nlb/issues/1
- [x] https://github.com/snaekobbi/pipeline-mod-mtm/issues/1
- [x] https://github.com/snaekobbi/pipeline-mod-sbs/issues/1
- [x] https://github.com/snaekobbi/pipeline-mod-dedicon/issues/1

**Comment by josteinaj** [comment]
Ansible seems good (haven't tried it). Could maybe use AWS hosting or similar as well instead of NLB-hosting if you think it makes things more maintainable and stable.

The plan is still to install using deb-files, right? And pipeline-assembly is already set up for that (although we need to test it a bit more I think). Will we be able to install DP2 modules as well with deb files you think? Also, the web ui...

**Comment by egli** [comment]
I am installing dp2 using debs and ansible. See https://github.com/sbsdev/sbs-infrastructure/tree/master/roles/pipeline2. I'm happy to help.

**Comment by bertfrees** [comment]
A have a bit of experience with Ansible too. External hosting is something we could possibly look at when we have a provisioning script. Yes, the plan would still be to use packages. For the web UI too. Installing DP2 modules with DEB packages is perfectly possible, and what I was planning to do with the agency-specific modules.

**Comment by bertfrees** [comment]
Done by Jostein
