### ISSUE TITLE
Java compatibility

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/issues#21]
For each component and for the whole system, make explicit in the developer documentation which Java versions are required. Possibly as an ultimate overview make a compatibility matrix.

All related issues:
- [x] https://github.com/joeha480/brailleutils/issues/23
- [x] https://github.com/joeha480/brailleutils/issues/63
- [x] https://github.com/joeha480/dotify/issues/7
- [x] https://github.com/joeha480/dotify/issues/124
- [x] https://github.com/joeha480/dotify/issues/136
- [x] https://github.com/daisy/pipeline-mod-braille/issues/59
- [x] https://github.com/snaekobbi/pipeline-mod-braille/issues/58
- [x] https://github.com/snaekobbi/pipeline-mod-dedicon/issues/7
- [x] https://github.com/daisy/pipeline-assembly/issues/107

**Comment by josteinaj** [comment]
pipeline-assembly was fixed last year. I don't know the state of dotify, since the issue referenced was closed 2 years ago, but I assume it's working since dotify is part of the latest pipeline 2 builds.

**Comment by bertfrees** [comment]
Note that this issue was also about documentation. Mentioned it in https://github.com/daisy/pipeline-tasks/issues/93.
