### ISSUE TITLE
HTML preview: make it easier to "go back" to job view

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/issues#26]

**Comment by bertfrees** [comment]
Don't think I understand. Does the back button of the browser not work maybe if you have previously clicked on page thumbnails?

**Comment by josteinaj** [comment]
Yes, as you navigate through the HTML preview, the fragment identifier in the browser changes, so you have to click "back" several times to get back to the job. I don't think something needs to change in the preview itself, it's nice to be able to refer to specific pages using fragments/anchors. I think maybe a solution would be to have the preview open in a new tab. Or maybe have a "back" link at the top of the html preview that takes you back to the previous URL, skipping all the anchors in your browser history (might need some javascript - I don't know).

**Comment by bertfrees** [comment]
I like opening the preview in a new tab.

A "back" link might work too although I don't have any idea how would that work.

**Comment by josteinaj** [comment]
Ok, let's do `target="_blank"` then. We can probably make all links open in a new tab - downloads will still just download; i.e. we don't need to check for an html file extension etc.

**Comment by josteinaj** [comment]
Closing this. Opened daisy/pipeline-webui#84.
