### ISSUE TITLE
HTML preview: support volumes

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/issues#27]

**Comment by bertfrees** [comment]
Yep, I've been looking into this but haven't found the time yet. This is quite important indeed.

**Comment by bertfrees** [comment]
Duplicate of https://github.com/daisy/pipeline-mod-braille/issues/87. This was fixed in https://github.com/daisy/pipeline-mod-braille/commit/9639e36102b1768ddfcbc1f44c1adaafe4a5ad3e.
