### ISSUE TITLE
More useful execution log output

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/issues#29]
This is some information that might be useful for braille experts to have:
- [ ] What happens during volume breaking
- [ ] Consequences due to hyphenation and long words either not fitting on a line, causing orphan/widows, etc.
- [ ] Characters that cannot be translated to braille due to them not being present in the braille table.
- [ ] What happens to tables, how are they laid out, when do they go from being rendered in one way as opposed to another way
- [ ] The location in the input file for all these messages
- [ ] In addition to being output in the execution log, summarize relevant issues and warnings in a job report, including the number of times each type occured
- [ ] How far into the book the conversion is (page number or anything else that can be counted, maybe say for each 100th paragraph something like "Processed {N*100} paragraphs...")
- [ ] What part of the conversion is currently being performed (translation, layout, volume breaking, etc.)
- [ ] Remove or hide warnings and errors that are expected, does not add any useful information, and is confusing for end-users

Feel free to add any other information that would be useful to this list.

**Comment by bertfrees** [comment]
Good points. Not all of them are as easy to implement. But for me usability is a very important topic in phase 3 of the project, so we're going to do what we can.

**Comment by dkager** [comment]
> How far into the book the conversion is ...

This is a direct request from our transcribers. Our current system shows a percentage indicator, but 'page X of Y' would also be good I think.

**Comment by bertfrees** [comment]
> - How far into the book the conversion is (page number or anything else that can be counted, maybe say for each 100th paragraph something like "Processed {N*100} paragraphs...")
> - What part of the conversion is currently being performed (translation, layout, volume breaking, etc.)

Related to this is https://github.com/daisy/pipeline-webui/issues/89.

**Comment by josteinaj** [comment]
@bertfrees should this issue be moved to daisy/pipeline-mod-braille ? And should the other open issues in this repository also be closed and moved to other repositories?

**Comment by bertfrees** [comment]
Yes we can move this issue and some other issues too. See https://github.com/snaekobbi/issues/issues/31. I'd just create new ones that reference the old ones though, nothing fancy.

**Comment by josteinaj** [comment]
Moved to: https://github.com/daisy/pipeline-mod-braille/issues/165
