### ISSUE TITLE
Merge snaekobbi/dotify with upstream

### ISSUE THREAD

**Issue by joeha480** [snaekobbi/issues#6]
The snaekobbi/dotify repo should be merged with upstream (or forked from it). Note that the two repos are based on different svn to git conversions, and therefore do not have common ancestors. In other words, manual copying may be required.

**Comment by bertfrees** [comment]
I don't think the fork contains any changes apart from the Gradle stuff, but that is already committed through SVN.

**Comment by joeha480** [comment]
Ok, great! Perhaps delete it then?

**Comment by bertfrees** [comment]
There are two issues and a pull request I'd like to keep for reference. I'll move them after you've migrated the issues.

**Comment by bertfrees** [comment]
I did this last week.
