### ISSUE TITLE
Finnish hyphenation for word-ending single vowels

### ISSUE THREAD

**Issue by jukkae** [snaekobbi/issues#8]
The official recommendation for hyphenation of word-ending single vowel syllables states that words should not be broken so that only a single letter is moved to the next line. For example, even though "uusia" is broken into syllables as "uu|si|a", it is recommended that it is hyphenated as "uu-sia".
This does not currently work with plain texhyph, but works with libhyphen.
The patterns were removed and tests written accordingly.
The patterns are:

```
2a.
2e.
2i.
2o.
2u.
2y.
2ä.
2ö.
```

**Comment by bertfrees** [comment]
Moved to https://github.com/celiafi/pipeline-mod-celia/issues/47
