### ISSUE TITLE
Support for brl:literal with ASCII braille

### ISSUE THREAD

**Issue by mixa72** [snaekobbi/issues#9]
The <code>brl:literal</code> element which is used to embed braille output in the source file should support not only Unicode braille but also ASCII braille. (https://github.com/snaekobbi/functional-testing/pull/17#issuecomment-108445742)

**Comment by bertfrees** [comment]
This will involve a conversion from ASCII to Unicode braille because we want to obtain a valid PEF.

**Comment by bertfrees** [comment]
Closing, see https://github.com/sbsdev/pipeline-mod-sbs/issues/35.
